### ISSUE TITLE
Translated strings in the json files are not preserved

### ISSUE THREAD

**Issue by barbogast** [bcabanes/gulp-angular-translate-extract#2]
I'm not sure if this is really an issue. My expectation was that gulp-angular-translate-extract preserves the translated strings in the json files. In other words: I'd like to use the following process:
1. When I run gulp-angular-translate-extract the first time it creates the json files for all languages.
2. Then I manually edit the json files to translate the extracted keys.
3. When I've added more keys to my source files I run gulp-angular-translate-extract. Now I expect my translations to be still present and the new keys added empty.

Is that the way gulp-angular-translate-extract is intended to be used?

If yes, than this is a bug report ;-) 

gulp-angular-translate-extract doesn't preserve my already translated strings. Everytime I run it a json file with only the keys present is created. The statistics say: `en_US statistics:  Updated: 0 / Deleted: 0 / New: 2`

**Comment by bcabanes** [comment]
Hi Koblaid,
First, thank you for your report!
Second, I looked into this issue and it seems to be a bug. 
I'm working on that right now. It should be the JSON parser that doesn't send the right value to the Merge process.

++

**Comment by bcabanes** [comment]
Just found & fix the issue https://github.com/bcabanes/gulp-angular-translate-extract/commit/8ff23a669fa2e2719a0b4e588e7f86971a4105cc. 
It was indeed the JSON parser that doesn't send the right value.
I will make a new release with the fix ASAP.

++

**Comment by bcabanes** [comment]
New version with the fix available now `v0.1.4` :grinning: 

Waiting from you to close the issue.

**Comment by barbogast** [comment]
Thanks for working on this. Unfortunately my translated strings still get overwritten. Maybe the problem is the options that I use?

I run it with 

``` javascript
{
  lang: ...,
  dest: ...,
  namespace: true,
  stringifyOptions: true,
}
```

**Comment by bcabanes** [comment]
Hi @Koblaid,
I've just released a new version with the fix available v0.1.5

**Comment by barbogast** [comment]
Great, now it works like a charm.

Thanks a lot :+1: 

Closing.

**Comment by aaronsama** [comment]
Hi @bcabanes 

I'm still experiencing this issue both in v0.1.5 and in v0.1.7. My gulp task below. Please let me know if I am doing something wrong. Thanks!

```
gulp.task('translate', function () {
  return gulp.src(['./www/templates/**/*.html', './www/js/**/*.js'], { base: './www' })
    .pipe(angularTranslate({
      lang: ['en', 'it']//,
      // defaultLang: 'en',
      // dest: 'locales/',
      // // prefix: 'js/i18n/locales/',
      // suffix: '.json',
      // stringifyOptions: true
    }))
    .pipe(gulp.dest('./www/js/i18n/locales/'));
});
```

**Comment by ayhansalami** [comment]
Hi @aaronsama 
I had the same problem.you should set `dest` option because if you don't set that your previous translations will disappear.
for example, if you want to save your language files in `languages` directory in below directory structure:

	-- root
		-- app
			-- languages


you should set your configuration as below:
```javascript
gulp.task('translate', function () {
  return gulp.src(['./app/**/*.html','./app/**/*.jade','./app/**/*.js'])
  .pipe(angularTranslate({
    lang: ['fa', 'en'],
    dest: 'app/languages',
    prefix: 'locale-',
    namespace: true,
    suffix: '.json'
  }))
  .pipe(gulp.dest('./app/'))
})
```
